### PR TITLE
server-side sorting of admin page

### LINKED ISSUE #3816: Sorting option on the admin page considers only the servers listed on the current page
### Bug description
Sorting option on the JupyterHub admin page considers only the servers listed on the current page.

#### Expected behaviour
All the servers should be sorted first and then paginated. (It may require to reload the list of servers...)

#### Actual behaviour
Clicking on one of the sorting option (User or Last Activity, e.g.) on the Admin page, sorts the list displayed on the current or actual page, not the whole.

### How to reproduce
1. Go to `/hub/admin` Admin page
2. Click on one of the up/down arrows in the header of the table
3. Click on Next at the bottom of the table
4. The pages are sorted separately

### Your personal set up
`docker image pull jupyterhub/jupyterhub`

 - OS: Ubuntu 20.04.4 LTS
 - Version(s): JupyterHub 2.0.0, Python 3.8.10
- <details><summary>Full environment</summary>
  
  ```
  alembic==1.7.3
  argon2-cffi==21.3.0
  argon2-cffi-bindings==21.2.0
  asttokens==2.0.5
  async-generator @ file:///tmp/wheelhouse/async_generator-1.10-py3-none-any.whl
  attrs @ file:///tmp/wheelhouse/attrs-21.2.0-py2.py3-none-any.whl
  backcall==0.2.0
  black==21.12b0
  bleach==4.1.0
  certifi @ file:///tmp/wheelhouse/certifi-2021.10.8-py2.py3-none-any.whl
  certipy @ file:///tmp/wheelhouse/certipy-0.1.3-py3-none-any.whl
  cffi @ file:///tmp/wheelhouse/cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
  charset-normalizer @ file:///tmp/wheelhouse/charset_normalizer-2.0.8-py3-none-any.whl
  click==8.0.3
  cryptography @ file:///tmp/wheelhouse/cryptography-36.0.0-cp36-abi3-manylinux_2_24_x86_64.whl
  cycler==0.11.0
  debugpy==1.5.1
  decorator==5.1.1
  defusedxml==0.7.1
  entrypoints @ file:///tmp/wheelhouse/entrypoints-0.3-py2.py3-none-any.whl
  executing==0.8.2
  fonttools==4.28.5
  greenlet @ file:///tmp/wheelhouse/greenlet-1.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  idna @ file:///tmp/wheelhouse/idna-3.3-py3-none-any.whl
  importlib-metadata @ file:///tmp/wheelhouse/importlib_metadata-4.8.2-py3-none-any.whl
  importlib-resources @ file:///tmp/wheelhouse/importlib_resources-5.4.0-py3-none-any.whl
  ipykernel==6.7.0
  ipython==8.0.0
  ipython-genutils==0.2.0
  ipywidgets==7.6.5
  jedi==0.18.1
  jhub-shibboleth-user-authenticator==0.1.6
  Jinja2 @ file:///tmp/wheelhouse/Jinja2-3.0.3-py3-none-any.whl
  jsonschema==3.2.0
  jupyter==1.0.0
  jupyter-client==6.1.12
  jupyter-console==6.4.0
  jupyter-core==4.7.1
  jupyter-telemetry @ file:///tmp/wheelhouse/jupyter_telemetry-0.1.0-py3-none-any.whl
  jupyterhub @ file:///tmp/wheelhouse/jupyterhub-2.0.0-py3-none-any.whl
  jupyterhub-idle-culler==1.2.1
  jupyterlab-widgets==1.0.2
  kiwisolver==1.3.2
  Mako @ file:///tmp/wheelhouse/Mako-1.1.6-py2.py3-none-any.whl
  MarkupSafe @ file:///tmp/wheelhouse/MarkupSafe-2.0.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
  matplotlib==3.5.1
  matplotlib-inline==0.1.3
  metakernel==0.28.2
  mistune==0.8.4
  mpmath==1.2.1
  mypy-extensions==0.4.3
  nbconvert==5.6.1
  nbformat==5.1.3
  -e git+https://github.com/jupyter/nbgrader@1ae2886e4e734554d8667c6e86861e83cc161451#egg=nbgrader
  nest-asyncio==1.5.4
  notebook==6.4.4
  numpy==1.22.1
  oauthlib @ file:///tmp/wheelhouse/oauthlib-3.1.1-py2.py3-none-any.whl
  octave-kernel==0.34.0
  packaging @ file:///tmp/wheelhouse/packaging-21.3-py3-none-any.whl
  pamela @ file:///tmp/wheelhouse/pamela-1.0.0-py2.py3-none-any.whl
  pandocfilters==1.5.0
  parso==0.8.3
  pathspec==0.9.0
  pexpect==4.8.0
  pickleshare==0.7.5
  Pillow==9.0.0
  platformdirs==2.4.1
  prometheus-client @ file:///tmp/wheelhouse/prometheus_client-0.12.0-py2.py3-none-any.whl
  prompt-toolkit==3.0.24
  ptyprocess==0.7.0
  pure-eval==0.2.1
  pycparser @ file:///tmp/wheelhouse/pycparser-2.21-py2.py3-none-any.whl
  pycurl==7.43.0.2
  Pygments==2.11.2
  pyOpenSSL @ file:///tmp/wheelhouse/pyOpenSSL-21.0.0-py2.py3-none-any.whl
  pyparsing @ file:///tmp/wheelhouse/pyparsing-3.0.6-py3-none-any.whl
  pyrsistent @ file:///tmp/wheelhouse/pyrsistent-0.18.0-cp38-cp38-manylinux1_x86_64.whl
  python-dateutil @ file:///tmp/wheelhouse/python_dateutil-2.8.2-py2.py3-none-any.whl
  python-json-logger @ file:///tmp/wheelhouse/python_json_logger-2.0.2-py3-none-any.whl
  pyzmq==22.3.0
  qtconsole==5.2.2
  QtPy==2.0.0
  rapidfuzz==1.6.2
  requests @ file:///tmp/wheelhouse/requests-2.26.0-py2.py3-none-any.whl
  rise==5.7.1
  ruamel.yaml @ file:///tmp/wheelhouse/ruamel.yaml-0.17.17-py3-none-any.whl
  ruamel.yaml.clib @ file:///tmp/wheelhouse/ruamel.yaml.clib-0.2.6-cp38-cp38-manylinux1_x86_64.whl
  scipy==1.7.3
  Send2Trash==1.8.0
  six @ file:///tmp/wheelhouse/six-1.16.0-py2.py3-none-any.whl
  SQLAlchemy==1.4.25
  stack-data==0.1.4
  sympy==1.9
  terminado==0.12.1
  testpath==0.5.0
  tomli==1.2.3
  tornado @ file:///tmp/wheelhouse/tornado-6.1-cp38-cp38-manylinux2010_x86_64.whl
  traitlets==5.1.0
  typing_extensions==4.0.1
  urllib3 @ file:///tmp/wheelhouse/urllib3-1.26.7-py2.py3-none-any.whl
  wcwidth==0.2.5
  webencodings==0.5.1
  widgetsnbextension==3.5.2
  zipp @ file:///tmp/wheelhouse/zipp-3.6.0-py3-none-any.whl
  ```
</details>

- <details><summary>Configuration</summary>
  
  
  ```python
  # jupyterhub_config.py
  c.JupyterHub.services = [
    { 'name': 'culler-service',
      'command': [
            sys.executable, '-m', 'jupyterhub-idle-culler', '--timeout=3600'
      ],
    },
    { 'name': 'formgrader-admin',
      'api_token': jhub_api_token
    },
    { 'name': '00YZ',
      'url': 'http://127.0.0.1:9999',
      'command': [
        'jupyterhub-singleuser',
        '--group=formgrade-00YZ',
        '--debug'
      ],
      'user': 'grader-00yz',
      'cwd': '/home/grader-00yz',
    },
  ]
  c.JupyterHub.load_roles = [
    {   'name':   'idle-culler-role',
        'scopes': [
            'list:users', 'read:users:activity',
            'read:servers', 'delete:servers', 'admin:users'
        ],
        'services': [ 'culler-service' ]
    },
    {
        'name':     'formgrade-role',
        'scopes':   [ 'read:users:groups', 'list:services', 'groups' ],
        'services': [ 'formgrader-admin' ]
    },
    # access courses by its tutors only:
    {   'name':   'role-00yz', # must be LOWERCASE!
        'scopes': [ 'access:services!service=00YZ' ],
        'groups': [ 'formgrade-00YZ' ]
    },
  ]
  c.JupyterHub.load_groups = {
    'formgrade-00YZ': [ 'grader-00yz' ],
    'nbgrader-00YZ': [],
  }
  c.JupyterHub.authenticator_class = 'jhub_shibboleth_user_authenticator.shibboleth_user_auth.ShibbolethUserAuthenticator'
  c.Authenticator.header_name = 'Niifpersonorgid'
  c.Authenticator.auth_state_header_names = [ 'Sn', 'Persistent-Id', 'Ou', 'Niifpersonorgid' ]
  ```
</details>

- <details><summary>Logs</summary>
  
  ```
  # No relevant logs.
  ```
</details>

### LINKED ISSUE #4482: Cannot perform a global sort by 'Running' status in the admin panel
### Bug description

The /hub/admin#/ endpoint shows a table of users and their servers. However, in jupyterhub-3.x the sorting seems to be broken. We're upgrading from 1.x where sorting by the 'Running' column in the ascending order would list all running servers. However, in jhub-3.x only running servers present on the current 'page' are shown. Since pagination only shows 50 entries per page other running servers are shown at the top of the pages they were paginated to. With a large list of users this sorting option becomes less than useful.

#### Expected behaviour

Sorting /hub/admin#/ by 'Running' in the ascending order should show all running servers on the first page(s) i.e. all running servers must be at the top of the list.

#### Actual behaviour

only running servers present on the current 'page' are shown. Since pagination only shows 50 entries per page other running servers are shown at the top of the pages they were paginated to.

### How to reproduce

1. Go to  /hub/admin#/
2. Click on 'Running' column header
3. Expect to see all running servers at the top of the table

### Your personal set up

 - OS:
 
 - Version(s): Conda environment on RHEL7
 

<details><summary>Full environment</summary>

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiofiles                  22.1.0             pyhd8ed1ab_0    conda-forge
aiosqlite                 0.18.0             pyhd8ed1ab_0    conda-forge
alembic                   1.10.3             pyhd8ed1ab_0    conda-forge
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py311hd4cff14_3    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
batchspawner              1.2.0              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blinker                   1.6.2              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py311hd4cff14_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
certipy                   0.1.3                      py_0    conda-forge
cffi                      1.15.1          py311h409f033_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
configurable-http-proxy   4.5.4                he2f69ee_2    conda-forge
cryptography              40.0.2          py311h9b4c7bb_0    conda-forge
debugpy                   1.6.7           py311hcafe171_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
gitdb                     4.0.10             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.31             pyhd8ed1ab_0    conda-forge
greenlet                  2.0.2           py311hcafe171_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.5.0              pyha770c72_0    conda-forge
importlib_metadata        6.5.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
ipykernel                 6.22.0             pyh210e3f2_0    conda-forge
ipython                   8.12.0             pyh41d4057_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jhub-remote-user-authenticator 0.1.0                    pypi_0    pypi
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter-server-mathjax    0.2.6              pyh5bfe37b_1    conda-forge
jupyter_client            8.2.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0           py311h38be061_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.5.0              pyhd8ed1ab_0    conda-forge
jupyter_server_fileid     0.9.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyter_server_ydoc       0.8.0              pyhd8ed1ab_0    conda-forge
jupyter_telemetry         0.1.0              pyhd8ed1ab_1    conda-forge
jupyter_ydoc              0.2.3              pyhd8ed1ab_0    conda-forge
jupyterhub                3.1.1              pyh2a2186d_0    conda-forge
jupyterhub-base           3.1.1              pyh2a2186d_0    conda-forge
jupyterhub-moss           6.0.0                    pypi_0    pypi
jupyterlab                3.6.3              pyhd8ed1ab_0    conda-forge
jupyterlab-git            0.41.0             pyhd8ed1ab_1    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.22.1             pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libcurl                   8.0.1                h588be90_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpq                     15.2                 hb675445_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
mako                      1.2.4              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.2           py311h2582759_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
nbclassic                 0.5.5              pyhb4ecaf3_1    conda-forge
nbclient                  0.7.3              pyhd8ed1ab_0    conda-forge
nbconvert                 7.3.1              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.3.1              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.3.1              pyhd8ed1ab_0    conda-forge
nbdime                    3.2.1              pyhd8ed1ab_0    conda-forge
nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
nodejs                    18.15.0              h8d033a5_0    conda-forge
notebook                  6.5.4              pyha770c72_0    conda-forge
notebook-shim             0.2.2              pyhd8ed1ab_0    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
openssl                   3.1.1                hd590300_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pamela                    1.0.0                      py_0    conda-forge
pandoc                    2.19.2               h32600fe_2    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       23.1               pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.2.0              pyhd8ed1ab_0    conda-forge
prometheus_client         0.16.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
psutil                    5.9.5           py311h2582759_0    conda-forge
psycopg2                  2.9.3           py311h968e94b_2    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycurl                    7.45.1          py311hae980a4_3    conda-forge
pydantic                  1.10.7                   pypi_0    pypi
pygments                  2.15.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.6.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.3          py311h2582759_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.3          h2755cc3_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.3             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py311hd4cff14_5    conda-forge
pyzmq                     25.0.2          py311hd6ccaeb_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.28.2             pyhd8ed1ab_1    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
ruamel.yaml               0.17.21         py311h2582759_3    conda-forge
ruamel.yaml.clib          0.2.7           py311h2582759_1    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                67.6.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlalchemy                2.0.9           py311h2582759_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
terminado                 0.17.1             pyh41d4057_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.3             py311h2582759_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.5.1              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
wrapspawner               1.0.1                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
y-py                      0.5.9           py311hfe55011_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
ypy-websocket             0.8.2              pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
c.Application.log_datefmt = '%Y-%m-%d %H:%M:%S'
c.JupyterHub.active_server_limit = 200
c.JupyterHub.authenticator_class = 'jhub_remote_user_authenticator.remote_user_auth.RemoteUserAuthenticator'
c.JupyterHub.bind_url = 'REDACTED'
c.JupyterHub.cleanup_servers = False
c.JupyterHub.concurrent_spawn_limit = 100
c.JupyterHub.cookie_max_age_days = 1
c.JupyterHub.db_url = 'REDACTED'
c.JupyterHub.extra_handlers = [(r"/api/batchspawner", 'batchspawner.api.BatchSpawnerAPIHandler')]
c.JupyterHub.hub_connect_url = 'REDACTED'
c.JupyterHub.logo_file = '/opt/jupyterhub/rc_jhub_logo.png'
c = get_config()
c.JupyterHub.spawner_class = 'wrapspawner.ProfilesSpawner'
c.Spawner.http_timeout = 300
c.ProfilesSpawner.profiles = [
      ( "Teaching - 1 CPU core, 2GB RAM, 2h", "1x2x2", "batchspawner.SlurmSpawner",
        dict(req_partition = "hpg-dev", req_nprocs = "1", req_runtime = "02:00:00", req_memory = "2gb" )),
      ("Interactive - 1 CPU core, 2GB RAM, 8h", "1x2x8", "batchspawner.SlurmSpawner",
        dict(req_partition = "hpg-dev", req_nprocs = "1", req_runtime = "8:00:00", req_memory = "2gb" )),
      ("Interactive - 1 CPU core, 4GB RAM, 12h", "1x4x8", "batchspawner.SlurmSpawner",
        dict(req_partition = "hpg-dev", req_nprocs = "1", req_memory = "1gb", req_runtime = "12:00:00")),
      ("Interactive - 1 CPU core, 8GB RAM, 12h", "1x8x8", "batchspawner.SlurmSpawner",
        dict(req_partition = "hpg-dev", req_nprocs = "1", req_memory = "8gb", req_runtime = "12:00:00")),
      ("Compute - 1 CPU core, 32GB RAM, 144h", "1x32x144", "batchspawner.SlurmSpawner",
        dict(req_nprocs = "1", req_memory = "32gb", req_runtime = "144:00:00")),
      ("Compute - 4 CPU cores, 32GB RAM, 144h", "4x32x144", "batchspawner.SlurmSpawner",
        dict(req_nprocs = "4", req_memory = "8gb", req_runtime = "48:00:00")),
      ("Compute - 4 CPU cores, 32GB RAM, 144h", "4x32x144", "batchspawner.SlurmSpawner",
        dict(req_nprocs = "4", req_memory = "32gb", req_runtime = "144:00:00")),
      ("Compute - 8 CPU cores, 32GB RAM, 144h", "8x24x144", "batchspawner.SlurmSpawner",
        dict(req_nprocs = "8", req_memory = "32gb", req_runtime = "144:00:00")),
      ("Compute - 16 CPU cores, 32GB RAM, 144h", "16x24x144", "batchspawner.SlurmSpawner",
        dict(req_nprocs = "16", req_memory = "32gb", req_runtime = "144:00:00")),
      ("Compute - 24 CPU cores, 32GB RAM, 144h", "24x32x144", "batchspawner.SlurmSpawner",
        dict(req_nprocs = "24", req_memory = "32gb", req_runtime = "144:00:00")),
      ("Compute - 4 CPU cores, 48GB RAM, 24h", "4x48x24", "batchspawner.SlurmSpawner",
        dict(req_nprocs = "4", req_memory = "40gb", req_runtime = "24:00:00")),
      ("Compute - 32 CPU cores, 120GB RAM, 72h", "32x120x72", "batchspawner.SlurmSpawner",
        dict(req_nprocs = "32", req_memory = "120gb", req_runtime = "72:00:00")),
      ("GPU Teaching - 1 GPU, 1 CPU core, 4GB RAM, 2h", "1x1x4x2", "batchspawner.SlurmSpawner",
        dict(req_partition = "gpu", req_nprocs = "1", req_memory = "4gb", req_runtime = "2:00:00", req_options="--gpus=1")),
      ("GPU Interactive - 1 GPU, 1 CPU core, 6GB RAM, 6h", "1x1x6x6", "batchspawner.SlurmSpawner",
        dict(req_partition = "gpu", req_nprocs = "1", req_memory = "6gb", req_runtime = "6:00:00", req_options="--gpus=1")),
      ("GPU Interactive - 1 GPU, 4 CPU cores, 24GB RAM, 8h", "1x4x24x8", "batchspawner.SlurmSpawner",
        dict(req_partition = "gpu", req_nprocs = "4", req_memory = "24gb", req_runtime = "8:00:00", req_options="--gpus=1")),
      ("GPU Interactive - 2 GPUs, 2 CPU cores, 12GB RAM, 6h", "2x2x12x6", "batchspawner.SlurmSpawner",
        dict(req_partition = "gpu", req_nprocs = "2", req_memory = "12gb", req_runtime = "6:00:00", req_options="--gpus=2")),
      ("GPU Compute - 2 GPUs, 2 CPU cores, 12GB RAM, 24h", "2x2x12x24", "batchspawner.SlurmSpawner",
        dict(req_partition = "gpu", req_nprocs = "2", req_memory = "12gb", req_runtime = "24:00:00", req_options="--gpus=2")),
      ("GPU Compute - 3 GPUs, 3 CPU cores, 18GB RAM, 24h", "2x2x18x24", "batchspawner.SlurmSpawner",
        dict(req_partition = "gpu", req_nprocs = "3", req_memory = "18gb", req_runtime = "24:00:00", req_options="--gpus=3")),
      ("GPU ML - 4 GPUs, 4 CPU cores, 24GB RAM, 24h", "4x4x24x24", "batchspawner.SlurmSpawner",
        dict(req_partition = "gpu", req_nprocs = "4", req_memory = "24gb", req_runtime = "24:00:00", req_options="--gpus=4")),
      ("GPU Large ML - 4 GPUs, 4 CPU cores, 64GB RAM, 72h", "4x4x64x72", "batchspawner.SlurmSpawner",
        dict(req_partition = "gpu", req_nprocs = "4", req_memory = "64gb", req_runtime = "72:00:00", req_options="--gpus=4")),
      ("GPU Large ML - 8 GPUs, 8 CPU cores, 64GB RAM, 72h", "8x8x64x72", "batchspawner.SlurmSpawner",
        dict(req_partition = "gpu", req_nprocs = "8", req_memory = "64gb", req_runtime = "72:00:00", req_options="--gpus=8")),
      ("GPU A100 SM - 1 GPUs, 2 CPU cores, 24GB RAM, 24h", "1x2x24x24", "batchspawner.SlurmSpawner",
        dict(req_partition = "gpu", req_nprocs = "2", req_memory = "24gb", req_runtime = "24:00:00", req_options="--gpus=1 --constraint=a100")),
]
c.BatchSpawnerBase.batch_submit_cmd = '/opt/slurm/bin/sbatch --parsable'
c.BatchSpawnerBase.batch_query_cmd = "/opt/slurm/bin/squeue -h -j {job_id} -o '%T %B'"
c.BatchSpawnerBase.batch_cancel_cmd = "/opt/slurm/bin/scancel {job_id}"
c.BatchSpawnerBase.req_srun = 'source /etc/profile.d/modules.sh; unset XDG_RUNTIME_DIR; export PATH=/apps/jupyterhub/1.1.0/bin:$PATH; /opt/slurm/bin/srun'
c.Spawner.cmd = ['jupyter-labhub']
c.Spawner.cpu_guarantee = 1
c.Spawner.cpu_limit = 1
c.Spawner.env_keep = ['PATH', 'PYTHONPATH', 'CONDA_ROOT', 'CONDA_DEFAULT_ENV', 'VIRTUAL_ENV', 'LANG', 'LC_ALL']
c.Spawner.start_timeout = 300
c.Authenticator.admin_users = 'http://10.13.143.123:8001'
c.PAMAuthenticator.check_account = True
c.PAMAuthenticator.encoding = 'utf8'
c.PAMAuthenticator.open_sessions = True
c.PAMAuthenticator.service = 'login'
```
</details>

<details><summary>Logs</summary>

```
No relevant logs.
```
</details>

### PR DESCRIPTION
**Pull request by minrk**
removes all in-page sort, which removes sort by admin, server name, sort by running, as those are not available from the API.

This builds on #4720 and #4721 to use the new `sort` parameter in the [GET /users API](https://jupyterhub.readthedocs.io/en/latest/reference/rest-api.html#operation/get-users) and persist it in the new view state.

This means sort, etc. are always global, no matter how many users there are (closes #3816)

Running column switches from sort to _filter_, matching the `?state` query parameter in the API (closes #4482). So while you can't show running servers _first_, you can show _only_ running servers.

needed some CSS on the column widths to avoid jumps when toggling active server filter.

demo:

https://github.com/jupyterhub/jupyterhub/assets/151929/1de74b6a-b30f-4fde-9b43-0b983668512b

draft because I haven't updated the tests, but it works

### CODE REVIEW

File: jsx/src/components/ServerDashboard/ServerDashboard.jsx [hunk 1]
```diff
@@ -417,42 +443,39 @@ const ServerDashboard = (props) => {
...
+                    name="active_servers"
+                    aria-label="only show active servers"
+                    checked={state_filter == "active"}
+                    onChange={(event) => {
+                      setStateFilter(event.target.checked ? "active" : null);
+                    }}
+                  />
+                  {state_filter == "active"
+                    ? " Active servers"
+                    : " All servers"}
```
Comment (consideRatio) [inline jsx/src/components/ServerDashboard/ServerDashboard.jsx:477]: all-servers-active-servers

This didn't yet feel as intuitive as I think we can make it.

> - [ ] **All servers**

My thinking seeing this: "Ah so if I check this I can see all servers instead of a subset of them - what I'm currently seeing if not all servers then?"

> - [x] **Active servers**

My thinking seeing this: "Ah so if I uncheck this I can see not only the active servers!"

---

I think it would be better to just have `Active servers` at all time here.

> - [ ] **All servers**

For me,



This didn't feel intuitive for me, thinking the label should be Active servers at all times - where a unchecked "Active servers" checkbox means "you don't only see active servers, because this is unchecked"

Comment (consideRatio) [reply jsx/src/components/ServerDashboard/ServerDashboard.jsx:477]: I think my suggestion is either:

```suggestion
                  " Active servers"
```

or

```suggestion
                  " Active servers filter"
```

---

With ` filter` added, I think it becomes a bit more clear that not having it checked will still include active servers - just that it also includes non-active servers as well. Not sure what I think is best among these choices.

Comment (minrk) [reply jsx/src/components/ServerDashboard/ServerDashboard.jsx:477]: I struggled with that, too! A separate label makes sense, but I worried about using too much horizontal space in the header. 'Running' also doesn't make a huge amount of sense.

I put it in the same place the sort control used to be, but maybe that isn't the best idea.

WDYT about putting it next to the name filter? It's also a filter, so that makes sense to me. And there's plenty of room up there.

Comment (consideRatio) [reply jsx/src/components/ServerDashboard/ServerDashboard.jsx:477]: Absolutely open to a relocation of checkbox+label, I'm not certain if I'd like it better or not - the key UX confusion point I perceived was the changing checkbox label. I think having it close to name filtering probably is good, so hmmm i'm :+1: for a relocation also!

**Comment by minrk** [comment]
I moved the active filter next to the name filter. There's lots more room up there.

As a result, I merged the 'Running' and 'Actions' column, since there wasn't anything 'Running' about it as it's not a sort column anymore.

Screenshot 2024-03-08 at 09 51 04

This lets the table flow and resize a bit nicer, because the button 'cell' actually spans 4 columns, so it doesn't get squished as much on narrow screens:

Screenshot 2024-03-08 at 09 55 32

**Review by consideRatio — APPROVED** [review]
Excellent, having `only` before makes it very clear, and we can afford to be verbose given the new available space there - nice!

I've attempted to do code review on these parts as well and didn't find something that seemed weird - but I also didn't have time to make sure I understood the details with full confidence. Adding tests remain, and you are on that already so I'll go for an approve!

**Comment by minrk** [comment]
alignment was bugging me, here's the buttons on a narrow screen now:

Screenshot 2024-03-08 at 10 19 46

Arguably, they should collapse into a hamburger menu, but that's one step too far for the level of refactoring I want to do here.

**Comment by minrk** [comment]
Thanks @consideRatio!

**Comment by kabilar** [comment]
cc @asmacdo
